GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Toki Talks - Identity and commitment",
  "author": "tokisuno",
  "url": "https://tokisuno.rocks/blog/posts/20250731/",
  "likes": 3,
  "userId": "6894f1310d6f13a69f285028"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Toki Talks - Rebounding from Hardship",
  "author": "tokisuno",
  "url": "https://tokisuno.rocks/blog/posts/20250710/",
  "likes": 3
}

###
DELETE http://localhost:3003/api/blogs/6890bced08c79075c28f4335
