GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Toki Talks - Identity and commitment",
  "author": "tokisuno",
  "url": "https://tokisuno.rocks/blog/posts/20250731/",
  "likes": 3,
  "userId": "6894f7031f3f35e978205282"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODlmNDE1MmY4NDRmN2U5NGMwMmUzOGQiLCJpYXQiOjE3NTUyNjc4NDZ9.lAp4DZQ8Elga9FBhtfyc-cVfR5znWQWa2D1FYqpJPQw

{
  "title": "Toki Talks - Rebounding from Hardship",
  "author": "tokisuno",
  "url": "https://tokisuno.rocks/blog/posts/20250710/",
  "likes": 3
}

###
DELETE http://localhost:3003/api/blogs/689e10c0213e63cec7dd19d7
